const mockData = [
  [
   "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/dress1.jpeg",
   "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/dress2.jpeg",
   "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/dress3.jpeg",
   "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/dress4.jpeg",
   "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/dress5.jpeg",
   "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/dress6.jpeg",
   "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/dress7.jpeg"
  ],
  [
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/fshorts1.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/fshorts2.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/fshorts3.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/fshorts4.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/fshorts5.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/fshorts6.jpeg"
  ],
  [
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/ftank1.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/ftank2.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/ftank3.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/ftank4.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/ftank5.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/ftank6.jpeg"
  ],
  [
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mat1.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mat2.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mat3.jpeg"
  ],
  [
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mhoodie1.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mhoodie2.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mhoodie3.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mhoodie4.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mhoodie5.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mhoodie6.jpeg"
  ],
  [
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mjoggers1.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mjoggers2.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mjoggers3.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mjoggers4.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mjoggers5.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mjoggers6.jpeg"
  ],
  [
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mshorts1.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mshorts2.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mshorts3.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mshorts4.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mshorts5.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mshorts6.jpeg"
  ],
  [
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mtank1.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mtank2.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mtank3.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mtank4.jpeg",
    "https://feclululemonpics.s3.us-east-2.amazonaws.com/FEC/mtank5.jpeg"
  ]
]

module.exports = mockData;